name: Deployment

on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: setup go tool chain
          uses: actions/setup-go@v5
          with:
            go-version: "1.22"

        - name: Set up app
          run: ./scripts/buildprod.sh
